### ISSUE TITLE
0 (zero) displayed on main page

### ISSUE THREAD

**Issue by decryp2kanon** [sugarchain-project/Sugarchain-Explorer#1]
![image](https://user-images.githubusercontent.com/60179867/95775837-26762400-0c91-11eb-8f22-ffab50732513.png)

![image](https://user-images.githubusercontent.com/60179867/95775886-40176b80-0c91-11eb-94db-33432265ab47.png)

**Comment by Nugetzrul3** [comment]
It’s just a letter counter, that’s all

**Comment by decryp2kanon** [comment]
![image](https://user-images.githubusercontent.com/60179867/95809589-24d24d80-0cdd-11eb-9fde-c75f43e57772.png)

great :+1:
